### ISSUE TITLE
The 'Pods-CustomApp' target has frameworks with conflicting names: imglykit.framework.

### ISSUE THREAD

**Issue by d3vhound** [imgly/pesdk-react-native#2]
Trying to use both video editor sdk and photo editor sdk so how would I go about doing so?

**Comment by schiewe** [comment]
With [release 2.1.1](https://github.com/imgly/pesdk-react-native/releases/tag/2.1.1) you can now use PhotoEditor SDK and VideoEditor SDK in the same project.
