### ISSUE TITLE
Platform is not defined in react-native-photoeditorsdk node_module

### ISSUE THREAD

**Issue by kurtesy** [imgly/pesdk-react-native#4]
After integrating the react native plugin to our app and running the app for iOS we are encountering error in react native debugger.

Version:
React Native: 0.59
iOS version: 11
react-native-photoeditorsdk: 2.0.1

Error Message:
```
Platform is not defined
handleException @ ExceptionsManager.js:74
ExceptionsManager.js:82 Unhandled JS Exception: Platform is not defined
```

<img width="530" alt="Screenshot 2020-01-07 at 2 46 32 PM" src="https://user-images.githubusercontent.com/8374574/71883482-8d900680-315c-11ea-9dc0-c554163b1c36.png">

On Further debugging i found that 

> Platform import from react-native is missing in index.js of react-native-photoeditorsdk
`import {NativeModules, Image} from 'react-native';`

<img width="1041" alt="Screenshot 2020-01-07 at 2 48 55 PM" src="https://user-images.githubusercontent.com/8374574/71883645-dcd63700-315c-11ea-94f4-bff9452dbbfb.png">

I can raise a PR for fixing this issue as its just a one liner change.

**Comment by schiewe** [comment]
You suggest changing the first line to `import {NativeModules, Image, Platform} from 'react-native';
`, right? We'll fix it upstream and release it very soon. Thanks for reporting.

**Comment by kurtesy** [comment]
Yes thats correct, thank you.

**Comment by schiewe** [comment]
[Release 2.1.0](https://github.com/imgly/pesdk-react-native/releases/tag/2.1.0) fixes this issue.
